name: dataafrik-platform

services:
  - name: frontend
    source_dir: /
    github:
      repo: wlivinston/dataweb
      branch: master
    build_command: npm install --legacy-peer-deps && npm run build
    run_command: npx serve -s dist -l $PORT
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: basic-xxs
    envs:
      - key: VITE_SUPABASE_URL
        type: SECRET
        scope: RUN_AND_BUILD_TIME
      - key: VITE_SUPABASE_ANON_KEY
        type: SECRET
        scope: RUN_AND_BUILD_TIME
      - key: NODE_ENV
        value: production
        scope: RUN_AND_BUILD_TIME
    routes:
      - path: /
    health_check:
      http_path: /

  - name: backend
    source_dir: backend
    github:
      repo: wlivinston/dataweb
      branch: master
    # force clean, lockfile-based install so deps (e.g., gray-matter) are present
    build_command: npm_config_ci=true npm ci --omit=dev --no-audit --loglevel=error
    run_command: npm start
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: basic-xxs
    envs:
      - key: SUPABASE_URL
        type: SECRET
      - key: SUPABASE_SERVICE_ROLE_KEY
        type: SECRET
      - key: SUPABASE_ANON_KEY
        type: SECRET
      - key: FRONTEND_URL
        value: https://www.dataafrik.com
      - key: NODE_ENV
        value: production
    routes:
      - path: /api
    health_check:
      http_path: /health

  - name: ml-hub
    source_dir: streamlit_apps
    github:
      repo: wlivinston/dataweb
      branch: master
    build_command: pip install -r requirements.txt
    # path is /ml, so set baseUrlPath for asset URLs
    run_command: streamlit run main.py --server.port $PORT --server.address 0.0.0.0 --server.baseUrlPath ml
    environment_slug: python
    instance_count: 1
    instance_size_slug: basic-xxs
    envs:
      - key: SUPABASE_URL
        type: SECRET
        scope: RUN_AND_BUILD_TIME
      - key: SUPABASE_ANON_KEY
        type: SECRET
        scope: RUN_AND_BUILD_TIME
    routes:
      - path: /ml
    # health hits the service root, not /ml
    health_check:
      http_path: /

domains:
  - domain: dataafrik.com
    type: PRIMARY
  - domain: www.dataafrik.com
    type: ALIAS

envs:
  - key: NODE_ENV
    value: production
    scope: RUN_AND_BUILD_TIME

alerts:
  - rule: DEPLOYMENT_FAILED
    disabled: false
  - rule: DOMAIN_FAILED
    disabled: false
