name: dataafrik-platform
services:
  - name: frontend
    source_dir: /
    github:
      repo: your-github-username/dataweb
      branch: main
    build_command: npm install && npm run build
    run_command: npm run preview
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: basic-xxs
    envs:
      - key: VITE_SUPABASE_URL
        value: https://wjeqwwilkbpqwuffiuio.supabase.co
        type: SECRET
      - key: VITE_SUPABASE_ANON_KEY
        value: your_dataweb_anon_key_here
        type: SECRET
      - key: NODE_ENV
        value: production
    routes:
      - path: /
    health_check:
      http_path: /
      initial_delay_seconds: 10
      interval_seconds: 10
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 3

  - name: backend
    source_dir: backend
    github:
      repo: your-github-username/dataweb
      branch: main
    build_command: npm install
    run_command: npm start
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: basic-xxs
    http_port: 3001
    envs:
      - key: SUPABASE_URL
        value: https://wjeqwwilkbpqwuffiuio.supabase.co
        type: SECRET
      - key: SUPABASE_SERVICE_ROLE_KEY
        value: your_supabase_service_role_key_here
        type: SECRET
      - key: SUPABASE_ANON_KEY
        value: your_dataweb_anon_key_here
        type: SECRET
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "3001"
    routes:
      - path: /api
    health_check:
      http_path: /api/health
      initial_delay_seconds: 10
      interval_seconds: 10
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 3

  - name: ml-hub
    source_dir: streamlit_apps
    github:
      repo: your-github-username/dataweb
      branch: main
    build_command: pip install -r requirements.txt
    run_command: streamlit run main.py --server.port $PORT --server.address 0.0.0.0
    environment_slug: python
    instance_count: 1
    instance_size_slug: basic-xxs
    http_port: 8501
    envs:
      - key: SUPABASE_URL
        value: https://wjeqwwilkbpqwuffiuio.supabase.co
        type: SECRET
      - key: SUPABASE_ANON_KEY
        value: your_dataweb_anon_key_here
        type: SECRET
    routes:
      - path: /ml
    health_check:
      http_path: /ml
      initial_delay_seconds: 15
      interval_seconds: 10
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 3

databases:
  - name: dataweb-db
    engine: PG
    version: "15"
    production: false

domains:
  - domain: dataafrik.com
    type: PRIMARY
  - domain: www.dataafrik.com
    type: ALIAS

envs:
  - key: NODE_ENV
    value: production
    scope: RUN_AND_BUILD_TIME

alerts:
  - rule: DEPLOYMENT_FAILED
    disabled: false
  - rule: DOMAIN_FAILED
    disabled: false
  - rule: HIGH_CPU
    disabled: false
    operator: GREATER_THAN
    value: 80
    window: 5m
  - rule: HIGH_MEMORY
    disabled: false
    operator: GREATER_THAN
    value: 80
    window: 5m
